mixed-port: 10808
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090

# authentication:
#  - "admin:admin"
#  - "user2:pass2"

dns:
  enable: true
  listen: 53
  nameserver:
    - 223.5.5.5

proxy-groups:
  - name: auto
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 600
    use:
      - popo
      - qianglie
    proxies:
      - "1.0x JP-BGP-C 日本"
      
proxy-providers:
  popo:
    type: file
    path: ./providers/popo.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  qianglie:
    type: file
    path: ./providers/qianglie.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600

rule-providers:
  proxy:
    type: file
    behavior: classical
    path: ./ruleset/proxy.yaml
  direct:
    type: file
    behavior: classical
    path: ./ruleset/direct.yaml
  adblock:
    type: file
    behavior: classical
    path: ./ruleset/adblock.yaml
rules:
 - RULE-SET,direct,DIRECT
 - RULE-SET,adblock,REJECT
 - GEOIP,CN,DIRECT
 - MATCH,auto
